Fetch token price range
GeneralMagicio/q-acc pull request #134
Opened 2024-09-25 12:00 UTC by ae2079

2024-09-25 22:23 UTC, kkatusic approved these changes

2024-09-26 02:15 UTC, lovelgeorge99 approved these changes

2024-09-26 08:54 UTC, aminlatifi requested changes

2024-09-26 08:54 UTC, aminlatifi commented on src/components/ProjectCard/ProjectHoverCard.tsx
> +  }, []);
This can be replaced by a `useQuery`
Like here https://github.com/GeneralMagicio/abc-launcher/blob/main/src/hooks/usePolTokenPrice.ts

2024-09-26 08:54 UTC, aminlatifi commented on src/components/ProjectCard/ProjectHoverCard.tsx
> +                    $ {POLPrice && (POLPrice * tokenPriceRange.max).toFixed(3)}
Simple `toFixed` is enough? we don't have any format method in our helper?

2024-09-26 08:54 UTC, aminlatifi commented on src/services/tokenPrice.service.ts
> +  const X = useMemo(() => {
Usually, `useMemo` must be used for complex processes. Otherwise, its state management burdens more load than recomputation.

2024-09-26 08:54 UTC, aminlatifi commented on src/services/tokenPrice.service.ts
> +  const maxPrice = useMemo(() => {
Likewise

2024-09-26 14:51 UTC, aminlatifi approved these changes
Thanks @ae2079

2024-09-26 14:56 UTC, merged