fixed donation cap error and copy change
GeneralMagicio/q-acc pull request #256
Opened 2024-10-23 20:23 UTC by lovelgeorge99

https://qacc.atlassian.net/browse/QACC-310
https://qacc.atlassian.net/browse/QACC-314

2024-10-24 09:31 UTC, aminlatifi requested changes

2024-10-24 11:58 UTC, lovelgeorge99 commented on src/components/RoundCountBanner.tsx
> -                ' of 4'
> We can fetch the total number of rounds from backend.

which query can provide me the round number?

2024-10-24 12:30 UTC, aminlatifi commented on src/components/RoundCountBanner.tsx
> -                ' of 4'
The number is not explicitly returned, you can get the list and use its size. 
(please cache it)
```graphql
  allRounds {
    ... on EarlyAccessRound {
      id
    }
  }
  ```

2024-10-28 12:27 UTC, MohammadPCh approved these changes
Thanks @lovelgeorge99

2024-10-28 12:32 UTC, merged